src/sicmutils/operator.clj, test/sicmutils/operator_test.clj
These are the most basic operations, they work OK, but are mainly limited to univariate literate-functions.  You can, for instance, now do this correctly, for literal-functions f and g:
```
[sicmutils.env] > ((D ((* (- D g)(+ D 1)) f)) 'x)
(+
(* -1 (((expt D 2) f) x) (g x))
(* -1 (g x) ((D f) x))
(* -1 ((D f) x) ((D g) x))
(* -1 ((D g) x) (f x))
(((expt D 2) f) x)
(((expt D 3) f) x))
```
Some multivariate literal-functions work, e.g.
```
[sicmutils.env] > (def ff (literal-function 'ff [0 0] 0))
ff
[sicmutils.env] > ((*  (partial 1)  (partial 0)) ff) 'x 'y)
(((partial 1) ((partial 0) ff)) x y)))))
[sicmutils.env] > (((-  D  D) ff) 'x 'y)
(down 0 0)))
```
but, on the whole, they require (mapped) arithmetic operations on structures - as we have discussed.  I'll be looking at those next.
=> Arithmetic operations for Operators

src/sicmutils/rational_function.clj
This fixes #25 and furthermore adds an additional method for the case [Ratio ::rational-function] of generic `mul`.
=> Add three rational-function methods to `mul`

.travis.yml, project.clj, src/sicmutils/generic.clj
This PR attempts to add https://github.com/cloverage/cloverage, to generate a Coverage report for `codecov.io`. I think that the macros in the project may be too difficult for cloverage to handle; many tests fail with cloverage's instrumentation attached, and a few of the namespaces completely fail to be instrumented.
I wanted to push this anyway as an example of how to set this up. Feel free to close; at least we'll have it around, and if we want this, and I get some time, I can submit the specific errors as bugs to cloverage.
=> Attempt at adding Cloverage with codecov support

src/sicmutils/expression.cljc, src/sicmutils/generic.cljc, test/sicmutils/expression_test.cljc, test/sicmutils/generic_test.cljc, test/sicmutils/runner.cljs
This got tricky! Macros always have something to teach me. This time it was about how to generate the correct runtime behavior from within the compile-time-expanding macro.
=> Convert sicmutils.{expressions, generic}

src/sicmutils/calculus/derivative.clj, src/sicmutils/complex.cljc, src/sicmutils/generic.cljc, src/sicmutils/matrix.clj, src/sicmutils/numbers.cljc, src/sicmutils/operator.clj, src/sicmutils/polynomial.clj, src/sicmutils/rational_function.clj, src/sicmutils/value.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/generic_test.cljc, test/sicmutils/numbers_test.cljc, test/sicmutils/value_test.cljc
This PR:
- adds a few (but not all) missing protocol methods to various types around the codebase
- moves the `v/Value` implementation for numbers into `value` itself, so no import's required to get this working
- modifies the `generic.{+, -, /, *} so they don't use `number?` anymore.
This lets the protocol do its work for allowing us to make the code more generic. Ratios and BigDecimal, etc won't return `true` for `number?` in Clojurescript. Complex numbers won't respond in Java, come to think of it. But these types implement `nullity?` and `unity?`, so we should totally be able to use these higher level generic functions and get some nice value out of them.
=> Consolidate numeric types, pave the way for more "generic" generics

src/sicmutils/complex.cljc, src/sicmutils/modint.cljc, src/sicmutils/numbers.cljc, src/sicmutils/numsymb.cljc, src/sicmutils/util.cljc, src/sicmutils/value.cljc, test/sicmutils/generic_test.cljc, test/sicmutils/value_test.cljc
This PR introduces a small hierarchy that lets us distinguish exact vs inexact numbers in cljs. I'll add more notes in the PR!
This PR follows #45 . If/Once that's merged I'll go ahead and point this at master. (I have it as a PR into a branch so it's reviewable in the UI.)
=> Introduce exact vs inexact number

src/sicmutils/polynomial_gcd.cljc, test/sicmutils/polynomial_gcd_test.cljc
Following up on a comment in a previous PR, this installs `sicmutils.polynomial/gcd` into the generic `gcd` implementation and migrates the tests to call the new thing.
=> Install generic polynomial GCD implementation

project.clj
The CLJSJS project published a bunch of the JS libraries I wrapped. This PR converts my personally published complex.js library over to the official cljsjs one.
=> Switch Complex dep from personal clojars to cljsjs

src/sicmutils/numerical/ode.cljc
This PR locks in a refactor that I used to integrate (yuk yuk) `sicmutils` with the Quil animation library:
https://github.com/sritchie/maturin/blob/master/src/maturin/better.clj#L33-L47
@littleredcomputer , I'm treading lightly since I know I'm in your domain now! Please treat this as a suggestion, not a final API that the Clojurescript port has to conform to.
=> Refactor `sicmutils.ode` to make it easier to explicitly trigger integration (1b)

src/data_readers.cljc, src/sicmutils/complex.cljc, test/sicmutils/complex_test.cljc
This is great. This lets us write `#sicm/complex "1 + 2i"` and get out a proper complex number, in both Clojure and Clojurescript.
=> Add complex reader literal support (2)

project.clj, src/data_readers.cljc, src/sicmutils/complex.cljc, src/sicmutils/euclid.cljc, src/sicmutils/generic.cljc, src/sicmutils/rational_function.cljc, src/sicmutils/util.cljc, src/sicmutils/value.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/euclid_test.cljc, test/sicmutils/generators.cljc, test/sicmutils/generic_test.cljc, test/sicmutils/laws.cljc, test/sicmutils/numbers_test.cljc, test/sicmutils/value_test.cljc
This PR:
- adds a reader literal for `#sicm/bigint` parsing at the repl and in source
- adds `test.check` generators for many of the types we use.
- adds test.check tests for semigroup, monoid, group, ring and field, with a few variations on each. These are nice gut checks of the `g/add`, `g/mul`, `g/sub`, `g/negate` and `g/invert` implementations.
=> Added algebraic laws, #sicm/bigint literal, tests for all numeric types (3)

src/sicmutils/numerical/derivative.cljc, src/sicmutils/numerical/interpolate/polynomial.cljc, src/sicmutils/numerical/interpolate/rational.cljc, src/sicmutils/numerical/interpolate/richardson.cljc, src/sicmutils/util/aggregate.cljc, test/sicmutils/numerical/interpolate/richardson_test.cljc
This PR:
- adds the ability to select specific columns from the tableau methods. This is important for recreating Simpson's method, etc, from the more general methods.
- fixes a bug where Richardson extrapolation would returns an endless sequence of `nil` if its input seq ran out.
brace yourself for more integral PRs!
=> Custom column selection for tableau methods, fix for Richardson (integrals #1)

package.json, src/sicmutils/CHANGELOG.md, src/sicmutils/expression.cljc, src/sicmutils/generic.cljc, src/sicmutils/numbers.cljc, src/sicmutils/value.cljc, test/sicmutils/calculus/vector_field_test.cljc, test/sicmutils/generic_test.cljc, test/sicmutils/sicm/ch5_test.cljc, test/sicmutils/sicm/ch6_test.cljc
This PR:
- adds a default implementation of `expt` based on a valid `mul`, `kind` and `one-like` implementation
- adds a default `sub`, based on `add` and `negate`
- default `div` if `mul` and `invert` are present
I was inspired by Doug McIlroy's gentle boast that these come for free in Haskell, and realized that we should make it easier for folks to implement these methods too.
=> Small fixes, default expt, sub, div implementations

src/sicmutils/series/impl.cljc, test/sicmutils/series/impl_test.cljc
This PR provides an implementation of power series using Clojure's lazy sequence API. The implementation follows Doug McIlroy's ["Power Series, Power Serious"](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.333.3156&rep=rep1&type=pdf) paper, with a few small extensions.
The PR itself is written as an essay, so I'll defer comments now. The goal of this is to provide a base for an upgrade of `series.cljc`.
=> Power series impl based on "Power Series, Power Serious" (series #1)

src/sicmutils/CHANGELOG.md, src/sicmutils/rules.cljc, test/sicmutils/rules_test.cljc
This PR adds more `sqrt` simplification rules to allow square roots to cancel out across a division boundary, with or without products in the numerator and denominator.
=> more sqrt simplifications

src/sicmutils/numerical/multimin/nelder_mead.cljc
We want to override nil even if it's explicitly passed.
=> Fix NPE bug

src/sicmutils/series/impl.cljc, test/sicmutils/series/impl_test.cljc
I was playing around to see if I could speed this up by generating the binomial series directly in the exponent code... and it looks like no, it's plenty fast now with a `zero?` check added in the mult method.
=> Speed up power series multiplication

jupyter/book-examples.ipynb
I'd like to remove this hint to my repository, it is now obsolete and thus confusing given the slack and zulip chats.
=> tidy up examples intro

src/sicmutils/matrix.cljc, src/sicmutils/structure.cljc, test/sicmutils/generators.cljc, test/sicmutils/matrix_test.cljc, test/sicmutils/structure_test.cljc
This PR pulls in laws for `transpose-outer`, `g/transpose` and `s:transpose` from the `scmutils` implementation. This makes me feel even better about our change in the previous PR.
=> Add transpose laws, more tests

src/sicmutils/abstract/function.cljc, src/sicmutils/calculus/coordinate.cljc, src/sicmutils/env.cljc, src/sicmutils/env/sci.cljc, src/sicmutils/env/sci/macros.cljc, src/sicmutils/expression/compile.cljc, src/sicmutils/mechanics/hamilton.cljc, test/sicmutils/env/sci_test.cljc, test/sicmutils/expression/render_test.cljc, test/sicmutils/runner.cljs
First stab at adding a sci environment. All public functions from `sicmutils.env` should work, plus the `literal-function` macro. `with-literal-functions` might work, but I haven't tested it yet. Could not yet figure out how to get `let-coordinates` and `using-coordinates` working. 
So far just tested with Clojure. Think I should at least add some basic tests before merging this.
Supersedes #199.
=> Add sicmutils.env.sci

CHANGELOG.md, src/sicmutils/expression/compile.cljc, test/sicmutils/env/sci_test.cljc, test/sicmutils/numerical/elliptic_test.cljc
Whoops, I removed the default `'user` namespace inclusion from the context, forcing an error here. Quick fix, plus changelog entries.
=> Fix tests for sci now that 'user isn't default

CHANGELOG.md, src/sicmutils/env/sci.cljc, src/sicmutils/structure.cljc, test/sicmutils/matrix_test.cljc, test/sicmutils/structure_test.cljc
Small one... this allows structures to render like this, if you use `pr` to print at the REPL (I know I still need to document how to make this look nice!):
```clojure
sicmutils.env> (saddle-FF)
[(up 8.246324826140356E-6 8.246324826140356E-6) (up 8.246324826140356E-6 8.246324826140356E-6)]
```
=> Add print-method implementation for `Structure`

src/sicmutils/env/sci.cljc, test/sicmutils/env/sci_test.cljc
A small follow-up to #216 and #230.
Makes the default sci context more batteries-included but allows consumers that are only interested in the sci namespace map to access that directly.
=> Expose sci namespaces and re-add bindings

CHANGELOG.md, src/sicmutils/expression/render.cljc, test/sicmutils/expression/render_test.cljc
`sicmutils.expression.render/*TeX-sans-serif-symbols*` binding to control if symbols longer than 1 char should have `\mathsf` applied.
=> Avoid sans-serif symbols

src/sicmutils/calculus/derivative.cljc, src/sicmutils/differential.cljc, test/sicmutils/calculus/derivative_test.cljc, test/sicmutils/differential_test.cljc
This PR adds an `*active-tags*` stack that allows us to save work in the case of a nested derivative. `*active-tags*` is a stack containing the tags of all nested calls; in #226 , this is going to save us trouble when deciding whether a `TapeCell` should wrap a `Differential` or vice versa if both show up in a computation.
=> Only trigger tag replacement in nested calls (suggested by GJS)

CHANGELOG.md, src/sicmutils/differential.cljc, src/sicmutils/generic.cljc
We need the derivative implementations for both reverse mode (#226 ) and forward mode AD. This PR moves the implementations to the metadata of our generic functions. @littleredcomputer , let me know if you like this change!
I've also added slightly better `:arglists` metadata for generics, and a few docstrings.
=> Move derivative implementations to generic metadata

CHANGELOG.md, src/sicmutils/expression.cljc, test/sicmutils/abstract/number_test.cljc
Prior to this change, we saw this:
```clojure
sicmutils.env> (pr-str (literal-number (simplify (* 'x 2))))
"clojure.lang.LazySeq@8ca01a75"
```
After, it all works as you'd expect!
=> Use pr-str inside Literal toString, allowing proper lazy sequence printing

src/sicmutils/differential.cljc, test/sicmutils/differential_test.cljc
@littleredcomputer , I'll accumulate changes you suggest in your autodiff reviews here, for PRs that I've already merged.
- update `Differential` docs
- remove `IFn` implementation for `Differential`
There is a better way to handle function differentials than this.
=> Doc updates, fixes from Colin's autodiff reviews

CHANGELOG.md, src/sicmutils/expression/render.cljc, src/sicmutils/series.cljc, test/sicmutils/expression/render_test.cljc
`sicmutils.render/->TeX` will render `Series` and `PowerSeries` as an infinite series (showing the first four terms). In the case of `PowerSeries`, it will default to `ax^n`.
=> Render series to TeX

CHANGELOG.md, demo.clj
This PR adds a proper namespace to `demo.clj`, to make it easier to use outside of `lein repl`. Addresses #263 .
=> Add proper namespace to demo.clj

CHANGELOG.md, src/sicmutils/env.cljc
Addresses #272 (thanks @pangloss for reporting this!) by adding missing `sicmutils.generic` methods to the `env` namespace.
CHANGELOG:
- Install `sicmutils.generic/{quotient,modulo,remainder,partial-derivative}`
into `sicmutils.env` (#273). Thanks to @pangloss for pointing out that these
were missing!
=> Add missing generic methods to env

CHANGELOG.md, src/sicmutils/env.cljc, src/sicmutils/mechanics/hamilton.cljc, src/sicmutils/util.cljc, src/sicmutils/value.cljc, test/sicmutils/env_test.cljc
- Function aliases in `sicmutils.env` now properly mirror over docstrings
and other `Var` metadata, thanks to
[Potemkin](https://github.com/clj-commons/potemkin)'s `import-def`. This
doesn't quite work in Clojurescript since we can't use `resolve` inside of a
macro (special form!).
=> Alias docstrings in aliased defs in sicmutils.env

CHANGELOG.md, src/sicmutils/env.cljc, src/sicmutils/expression/render.cljc, test/sicmutils/env_test.cljc, test/sicmutils/expression/render_test.cljc
This PR gives `->TeX` the ability to emit its form wrapped in an equation environment; optionally, the user can set a label.
- #280 adds a new `:equation` keyword argument to `sicmutils.render/->TeX`. If
you pass a truthy value to `:equation`, the result will be wrapped in an
equation environment. `:equation <string>` will insert a `\\label{<string>}`
entry inside the equation environment.
- `sicmutils.env/->tex-equation` is identical to `#(sicmutils.render/->TeX %
:equation true)`; If you pass a `:label` keyword argument to
`->tex-equation` it will be forwarded to `->TeX`, creating the expected
label entry.
=> Add optional :equation (and label) arguments to render/->TeX

CHANGELOG.md, src/sicmutils/expression/render.cljc, test/sicmutils/expression/render_test.cljc
I'm changing the default down tuple rendering to match scmutils style because a lot of the exercises from SICM end up being ULTRA wide if we render them this way. I think the square braces are already a nice touch. @littleredcomputer , I know you made a deliberate choice to _not_ do this, so I'm submitting this to you for judgement!
I also added missing handling for `prime` and `primeprime` suffixed symbols.
`scmutils` does nothing special for `'qprimeprimeprime`, while this implementation nests exponents. I am bad / uneducated with regexes... anyone have a suggestion for how to match >1 instances of `"prime"`, ending with newline, and do the right thing in the renderer?
- #283 changes the default `TeX` rendering style for `down` tuples to vertical
vs horizontal.
- …
=> prime, primeprime TeX rendering, change down to vertical by default

CHANGELOG.md, src/sicmutils/env.cljc, src/sicmutils/mechanics/hamilton.cljc, src/sicmutils/mechanics/lagrange.cljc, test/sicmutils/mechanics/lagrange_test.cljc
- #284 added:
- new functions `sicmutils.mechanics.lagrange/acceleration-tuple` for creating
the acceleration entry in a local tuple
- `sicmutils.mechanics.lagrange/acceleration` for extracting the acceleration
component of a local tuple
- An upgraded `sicmutils.mechanics.lagrange/F->C` to handle local tuples of
arbitrary length. This version of `F->C` is more general than the version
from the textbook that was previously included.
- These are all aliased in `sicmutils.env`, along with a new `Γ-bar` alias for
`sicmutils.mechanics.lagrange/Γ-bar`.
=> Generalize F->C, add more accessors to mechanics.lagrange

.github/workflows/release.yml, doc/faq.adoc, project.clj
The "publish" action wasn't triggering because I had the event wrong! I've fixed that and added a reference to Peek from @light-matters and @MagusMachinae.
=> Add Peek reference, fix github workflow issue on release

CHANGELOG.md, src/sicmutils/expression.cljc, test/sicmutils/expression_test.cljc
This PR addresses the issue @daslu raised in #291.
- #292 fixes a `StackOverflow` that would sometimes appear when comparing
symbolic expressions to non-expressions. `(= (literal-number x) y)` now
returns true if `(= x y)` (AND if `y` is not a collection!), false otherwise.
#255 is currently blocking pass-through equality with collections. Thanks to
@daslu for the report here!
=> fix comparison between Literal and non-literals

CHANGELOG.md, src/sicmutils/complex.cljc, src/sicmutils/expression/compile.cljc, src/sicmutils/expression/render.cljc, src/sicmutils/generic.cljc, src/sicmutils/numbers.cljc, src/sicmutils/numsymb.cljc, src/sicmutils/ratio.cljc, test/sicmutils/collection_test.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/numbers_test.cljc
This is a follow-up to #278. Here's a test function:
```clojure
(println
(->infix
(g/floor (g// (g/floor (g/modulo 'n 'x)) 'n))))
```
Demo for some riffs on that:
=> rendering impls for floor, ceil, integer-part, fractional-part, modulo, remainder

src/sicmutils/generic.cljc
It turns out `[[]]` style links don't resolve inside of backticks!
=> Docs updates from 0.16.0 release cljdoc inspection

CHANGELOG.md, src/sicmutils/env.cljc
This PR adds the mathematical constants `phi` and `e` bound to, respectively, `sicmutils.env/{phi,euler}`.
=> add e, phi mathematical constants

CHANGELOG.md, src/sicmutils/env.cljc
This gives users a way to build these things identical to the Clojure way.
=> Alias u/bigint into sicmutils.env for cljs only

README.md
The goal of this PR is to add a nice screenshot of Nextjournal to the Quickstart section in the README.
cc: @sritchie
=> Add screenshot of Nextjournal to Quickstart in README

CHANGELOG.md, deps.edn, src/sicmutils/complex.cljc, src/sicmutils/env.cljc, src/sicmutils/ratio.cljc, src/sicmutils/util.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/numbers_test.cljc
Small improvements, plus an SCI version bump. I've changed all JS property access to `goog.object/get`, which I HOPE will fix the bug in nextjournal in production, where `(imag-part (complex 1 2))` returns nil.
- #310: `g/make-rectangular` and `g/make-polar` now return non-Complex numbers
on the JVM if you pass `0` for the (respectively) imaginary or angle
components. Previously this behavior only occurred on an integer 0; now it
happens with 0.0 too, matching CLJS.
- `sicmutils.ratio/{ratio?,rationalize}` and are now aliased into `sicmutils.env` in Clojurescript. 
`sicmutils.complex/complex?` is aliased into `sicmutils.env` for both platforms.
=> slightly better test in bigint?

CHANGELOG.md, src/sicmutils/operator.cljc, src/sicmutils/simplify/rules.cljc, test/sicmutils/operator_test.cljc
This PR adds a simplifier that can properly handle the `name` field for operators.
The scmutils codebase just uses the normal simplifier, which can re-order arguments; this is no good! I think the only simplification we should EVER perform is turning multiplication into exponentiation.
@littleredcomputer what do you think?
=> Associative, non-commutative simplifier for operator names

CHANGELOG.md, src/sicmutils/abstract/function.cljc, src/sicmutils/calculus/derivative.cljc, src/sicmutils/differential.cljc, src/sicmutils/expression/render.cljc, src/sicmutils/generic.cljc, src/sicmutils/numsymb.cljc, src/sicmutils/operator.cljc, src/sicmutils/simplify/rules.cljc, test/sicmutils/abstract/number_test.cljc, test/sicmutils/expression/render_test.cljc, test/sicmutils/operator_test.cljc
I buckled and added to the simplifier for operators. Now `identity` gets stripped out of products. This will cause problems if someone names a NEW operator `identity`... but let's just hope no one does that!
From the CHANGELOG, this PR adds:
- symbolic boolean implementations for `sym:=`, `sym:and`, `sym:or` and
`sym:not` with infix, latex and JavaScript renderers.
- `sym:derivative`, for purely symbolic derivatives
The boolean operators will act just like `=`, `and` and `or` on booleans, and
appropriately respond if just one side is a boolean. If both sides are
symbolic, These return a form like `(= a b)`, `(and a b)` or `(or a b)`.
The functions currently live in `sicmutils.numsymb` only; access them via
`(numsymb/symbolic-operator <sym>)`, where `<sym>` is one of `'=`, `'and`,
`'or`, …
=> Add symbolic derivative, boolean operations

CHANGELOG.md, src/sicmutils/expression/render.cljc, test/sicmutils/expression/render_test.cljc
cc @kloimhardt , @littleredcomputer ...
From @kloimhardt :
> I just discovered that in sicmutils 0.16.0 the TeX representation of a (down ...) tuple is a column in square brackets. Not a row anymore. Is it possible to make that column visualization optional via setting some global variable (and set the default to the old row setting)? I think covectors should be displayed as rows whenever visually possible.
> Rationale: One main advantage of sicmutils over Mathematica is, that the distinction between covector and (contravariant) vector is built in at the core. I think most of the hardship in understanding Analytical Mechanics (and books like Arnold) stem from the fact that students grow up with just one type of vector and the corresponding easy to use vector products (inner product and …
=> Change default down-tuple rendering style to horizontal

CHANGELOG.md, src/sicmutils/polynomial.cljc, src/sicmutils/polynomial/factor.cljc, src/sicmutils/polynomial/gcd.cljc, src/sicmutils/simplify.cljc, test/sicmutils/calculus/manifold_test.cljc, test/sicmutils/function_test.cljc, test/sicmutils/polynomial/gcd_test.cljc
- #329 fixes a bug where the simplifier couldn't handle expressions like `(sqrt
(literal-number 2))`, where literal numbers with no symbols were nested inside
of symbolic expressions.
=> Fix simplifier bug with exprs like (sqrt (literal-number 2))

CHANGELOG.md, src/sicmutils/matrix.cljc, src/sicmutils/structure.cljc, test/sicmutils/matrix_test.cljc, test/sicmutils/structure_test.cljc
- #330 adds `g/real-part` and `g/imag-part` implementations for
`sicmutils.structure.Structure` and `sicmutils.matrix.Matrix` instances. These
pass through to the entries in the structure or matrix.
=> add real-part, imag-part implementations for structures, matrices

CHANGELOG.md, src/sicmutils/matrix.cljc, src/sicmutils/structure.cljc, test/sicmutils/matrix_test.cljc, test/sicmutils/structure_test.cljc
This PR installs `g/make-rectangular` and `g/make-polar` impls for structures and matrices. This lets us easily build complex matrices and structures from real components.
Closes #194.
=> Install make-{polar, rectangular} for structures and matrices

CHANGELOG.md, src/sicmutils/collection.cljc, test/sicmutils/collection_test.cljc
- #334 adds implementations of `g/add` and the `sicmutils.value.Value` protocol
for clojure's Set data structure. Addition is defined as set union, and
`(zero-like <set>)` returns the empty set.
- #334 implements `g/add`, `g/negate` and `g/sub` for Clojure's Map data
structure. Map addition is defined as a merge using `g/add` on clashing
values; `g/sub` is the same, but any values on the right side not on the left
side are negated.
Maps can also be multiplied with scalars (commutatively) or divided (scalar on
the right side only) by scalars. This, plus the commutative group property
declared above, mean that Clojure's maps are sparse vector spaces over
anything that responds true to `sicmutils.value/scalar?`... currently anything
in the numeric tower up to complex, …
=> Implement add for sets, add, sub, negate for maps

CHANGELOG.md, src/sicmutils/collection.cljc, test/sicmutils/collection_test.cljc
- #335 implements `g/make-rectangular`, `g/make-polar` `g/real-part` and
`g/imag-part` for clojure's Map data structure. Maps are treated as sparse
vectors, any missing key on either side of `make-rectangular` or
`make-polar`is treated as a 0 (rather than an error because the keys don't
match, as in vectors).
=> make-rectangular, make-polar, imag-part, real-part for maps

CHANGELOG.md, src/sicmutils/calculus/curvature.cljc, src/sicmutils/calculus/form_field.cljc, src/sicmutils/env.cljc, src/sicmutils/env/sci.cljc, src/sicmutils/operator.cljc, test/sicmutils/calculus/curvature_test.cljc, test/sicmutils/calculus/vector_field_test.cljc, test/sicmutils/collection_test.cljc, test/sicmutils/fdg/ch7_test.cljc, test/sicmutils/operator_test.cljc, test/sicmutils/runner.cljs
- #337:
- adds `sicmutils.calculus.curvature`, with these new functions and many tests
from the classic "Gravitation" book:
`Riemann-curvature`, `Riemann`, `Ricci`, `torsion-vector`, `torsion` and
`curvature-components`
- If you combine `Operator` instances with non-equal `:subtype` fields, the
returned operator now keeps the parent subtype (or throws if one is not a
subtype of the other).
- `Operator` instances now ignore any `identity?`-passing operator on the left
or right side of operator-operator multiplication. Contexts are still
appropriately merged.
- Similarly, `Operator` addition ignores `zero?` operators on the left or
right side, and subtraction ignores `zero?` operators on the right right.
- form fields now have NO identity operator, since they multiply by …
=> Port curvature.scm, fix operator behavior

src/sicmutils/env.cljc
The docstring for the Euler–Mascheroni constant was describing Euler’s number instead of the Euler–Mascheroni constant.
Alternatively, one can fix this by adjusting the number to be Euler's number. I've created a merge request for that [here](https://github.com/sicmutils/sicmutils/pull/352).
One of the two merge requests should be rejected depending on which solution is preferred.
=> Change docstring of Euler–Mascheroni constant

CHANGELOG.md, src/pattern/rule.cljc, src/sicmutils/env/sci.cljc, src/sicmutils/env/sci/macros.cljc, test/sicmutils/env/sci_test.cljc
This PR adds SCI support for all macros and functions in the new pattern matching namespaces, and adds these to the namespaces exposed via `sicmutils.env.sci`.
@pangloss, this double-macro-writing thing is a touch annoying, but totally worth it for SCI compatibility. You might take a peek at what I had to do here to get it working for your library!
=> Add SCI support for new pattern matching library

test/sicmutils/rational_function_test.cljc
Square and cube don't demote to coefficient; in the contrived generative testing situation, we sometimes make not-totally-reduced RFs, so `rf/mul` drops to coefficient but square and cube don't bother (since usually squaring or cubing wouldn't have that effect).
The solution is to force the RationalFunction instance to the left, since it can handle equality with non-RF instances.
=> flaky test fix for rational functions

CHANGELOG.md, deps.edn, project.clj, test/sicmutils/polynomial_test.cljc
#372 bumps the `Fraction.js` dependency to `4.1.1`.
=> Bump fraction.js dependency to 4.1.1

CHANGELOG.md, src/sicmutils/calculus/basis.cljc, src/sicmutils/calculus/coordinate.cljc, src/sicmutils/calculus/covariant.cljc, src/sicmutils/calculus/manifold.cljc, src/sicmutils/simplify.cljc, test/sicmutils/calculus/covariant_test.cljc, test/sicmutils/calculus/curvature_test.cljc, test/sicmutils/examples/rigid_rotation_test.cljc, test/sicmutils/fdg/ch7_test.cljc, test/sicmutils/generators.cljc, test/sicmutils/structure_test.cljc
This PR addresses issues noticed by @phasetr in ch7 of FDG. I also noticed a number of tests in `covariant_derivative.scm` that I had missed; porting those exposed a bug in the text, which is fixed as of this PR.
- `sicmutils.calculus.coordinate/generate` moves to
`sicmutils.calculus.manifold/c:generate`; this supports a bugfix where
1-dimensional manifolds like `R1-rect`, aka `the-real-line`, return a
coordinate prototype of a single element like `t` instead of a structure
with a single entry, like `(up t)`. Thanks to @phasetr for the bug report
that led to this fix, and @gjs for finding and fixing the bug.
- `same.ish/Approximate` implemented for `sicmutils.structure/Structure`,
allowing `ish?` comparison of `up` and `down` structures with approximate
entries. …
=> Add ch7, covariant tests

CHANGELOG.md, package.json, src/sicmutils/calculus/coordinate.cljc, src/sicmutils/env.cljc, src/sicmutils/env/sci/macros.cljc, src/sicmutils/function.cljc, src/sicmutils/util.cljc, src/sicmutils/util/def.cljc, test/sicmutils/env/sci_test.cljc, test/sicmutils/fdg/ch10_test.cljc, test/sicmutils/fdg/ch11_test.cljc, test/sicmutils/fdg/ch1_test.cljc, test/sicmutils/fdg/ch2_test.cljc, test/sicmutils/fdg/ch3_test.cljc, test/sicmutils/fdg/ch5_test.cljc, test/sicmutils/fdg/ch7_test.cljc, test/sicmutils/fdg/ch8_test.cljc, test/sicmutils/fdg/ch9_test.cljc, test/sicmutils/fdg/einstein_test.cljc, test/sicmutils/function_test.cljc
- #393:
- Forms like `(let-coordinates [(up x y) R2-rect] ...)` will now work even if
`up` is not present in the environment. Previously this syntax was valid,
but only if `up` had been imported.
- Adds the `sicmutils.calculus.coordinate/define-coordinates` macro, also
aliased into `sicmutils.env`. This macro allows you to write forms like
```clj
(define-coordinates (up t x y z) spacetime-rect)
(define-coordinates [r theta] R2-polar)
```
and install set of bindings for a manifold's coordinate functions, basis
vector fields and basis form fields into a namespace. This is used liberally
in Functional Differential Geometry. (You might still prefer `let-coordinates`
for temporary binding installation.)
- Converts many of the `sicmutils.fdg` test namespaces to use the new …
=> Add define-coordinates implementation

CHANGELOG.md, src/sicmutils/collection.cljc, test/sicmutils/calculus/covariant_test.cljc, test/sicmutils/calculus/derivative_test.cljc
This PR fixes an issue I encountered when converting Lie.scm in the scmutils codebase. One of the examples errored for me instead of returning the expected value.
Figuring this out helped me tidy up an edge case with derivatives of functions that return maps. I'll add my email to GJS with the scmutils problem details as an issue comment.
=> Fix type bug in covariant.cljc tests, bug w/ derivatives of fns returning maps

CHANGELOG.md, README.md, deps.edn, project.clj, src/sicmutils/env/sci.cljc, src/sicmutils/env/sci/macros.cljc, src/sicmutils/util/def.cljc, test/sicmutils/env/sci_test.cljc, test/sicmutils/fdg/ch1_test.cljc
Woohoo, thanks @borkdude for the help with a local repro.
- #396:
- fixes a bug in the SCI version of `define-coordinates` which didn't allow
any rebinding of manifolds.
- Removes the `bindings` key from `sicmutils.env.sci/context-opts`.
https://github.com/babashka/sci/issues/637 is a bug with variable rebinding
that occurs when `:bindings` is in play. Instead of relying on this key,
evaluate `(require '[sicmutils.env :refer :all])` against your SCI
environment to get all bindings.
=> Fix bug with define-coordinates in sci macro

CHANGELOG.md, src/sicmutils/calculus/manifold.cljc, test/sicmutils/calculus/manifold_test.cljc
I had missed that this is how the original scmutils version worked!
- `sicmutils.calculus.manifold/typical-coords` now returns generated coordinate
symbols that start with the same symbol as the coordinate system's prototype,
like:
```clj
(typical-coords R2-polar)
(up x065308 x165309)
(typical-coords
(with-coordinate-prototype R2-polar (up 'r 'theta)))
(up r65312 theta65313)
```
=> prepend prototype symbol in typical-coords

CHANGELOG.md, src/pattern/match.cljc, test/pattern/match_test.cljc
This PR fixes an issue discovered by @AdamHaber, where pattern binding failed on false or nil values.
=> Allow pattern matches to match nil, false

CHANGELOG.md, src/sicmutils/expression.cljc, src/sicmutils/numerical/quadrature/midpoint.cljc, src/sicmutils/numerical/quadrature/trapezoid.cljc, src/sicmutils/structure.cljc, test/sicmutils/abstract/number_test.cljc, test/sicmutils/calculus/connection_test.cljc, test/sicmutils/calculus/curvature_test.cljc, test/sicmutils/calculus/hodge_star_test.cljc, test/sicmutils/calculus/tensor_test.cljc, test/sicmutils/differential_test.cljc, test/sicmutils/numerical/quadrature/riemann_test.cljc, test/sicmutils/numerical/quadrature/trapezoid_test.cljc, test/sicmutils/polynomial_test.cljc, test/sicmutils/structure_test.cljc
- latest: convert `doall` calls to `run!`, `dorun` or `mapv` where applicable.
In cases where we were trying to force side effects (mostly in the tests),
this change prevents the environment from retaining the full sequence. This
will save memory!
=> Convert doall calls to run!, dorun and mapv

CHANGELOG.md, src/sicmutils/numbers.cljc, src/sicmutils/simplify/rules.cljc, test/sicmutils/function_test.cljc, test/sicmutils/numbers_test.cljc, test/sicmutils/simplify/rules_test.cljc
This PR fixes #439 :
- Modifies `(g/exp 0)` to return an exact 1, vs the previous `1.0`.
- Fixes a bug in `sicmutils.rules/exp-contract` leftover from the port from
Scheme. Thanks to @adamhaber for pointing this out!
=> Bugfix in exp-contract rules, exact result from (exp 0)

CHANGELOG.md, src/sicmutils/util/permute.cljc, test/sicmutils/util/permute_test.cljc
fixes #441 by upgrading the implementations of `sicmutils.util.permute/{factorial,number-of-combinations}` to be able to handle large inputs. Thanks to @swapneils for the report.
=> Make factorial, number-of-combinations more efficient

CHANGELOG.md, src/sicmutils/complex.cljc, src/sicmutils/function.cljc, src/sicmutils/generic.cljc, src/sicmutils/numsymb.cljc, src/sicmutils/structure.cljc, test/sicmutils/abstract/number_test.cljc, test/sicmutils/structure_test.cljc
- Implements `IKVReduce` and `Reversible` for structures. This enables `rseq`
and `reduce-kv` to work with structures.
- Removes a `reduced` shortcut condition in `sicmutils.generic/*` that was
causing multiplications of the form `(* 0 0 (up 0 0))` to shortcut and
return `0` instead of the appropriate structural form.
- the `atan` implementation for symbolic numbers is now careful not to return
a floating point number in the case of a 0 argument in the second position.
Additionally, it now returns symbolic `pi` or 0 in the case of `0` in the y
argument for positive and negative `x` argument, respectively, and symbolic
`(/ pi 2)` or `(- (/ pi 2))` for a 0 `x` argument and respective positive or
negative `y` argument.
=> atan2 symbolic upgrade, misc fixes

CHANGELOG.md, src/pattern/match.cljc, src/sicmutils/simplify.cljc, test/sicmutils/structure_test.cljc
- In `pattern.match` and all rules, things that respond true to `sequential?`
but not `seq?` or `vector?` (many of the sicmutils types, like structures and
the upcoming Quaternion type) were being converted to `seq` and treated as
sequence matchers vs literal matchers. This no longer happens, and structures
etc are treated as literal matchers.
=> Fix for pattern matcher accidentally seq-ing structures, etc

CHANGELOG.md, src/sicmutils/abstract/number.cljc, src/sicmutils/calculus/indexed.cljc, src/sicmutils/complex.cljc, src/sicmutils/env.cljc, src/sicmutils/numsymb.cljc, src/sicmutils/simplify/rules.cljc, src/sicmutils/structure.cljc, test/sicmutils/abstract/number_test.cljc, test/sicmutils/calculus/derivative_test.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/env_test.cljc, test/sicmutils/simplify/rules_test.cljc, test/sicmutils/simplify_test.cljc
- Use `Math/E` instead of `(Math/exp 1)` for euler's constant in
`sicmutils.env`.
- Fix bug in `sicmutils.calculus.indexed`, in a case where either input was
missing an `up` or `down`index type.
- symbolic `dot-product` and `inner-product`
- `inner-product` now defaults to `dot-product` for scalar instances. This is
correct for all numeric types we currently have, since `complex` is the only
tough case, and it has real coefficients.
- simplify now does NOT freeze expressions before simplifying. This allows
complex numbers to survive simplification, since they freeze to `(complex
<re> <im>)`.
- big rewrite in `sicmutils.simplify.rules`, to convert all of the frozen
matchers like `(complex 1 2)` into matchers that actually bind to a
complex number.
- more rules in …
=> Symbolic/complex dot-product, complex fixes

CHANGELOG.md, src/sicmutils/algebra/fold.cljc, src/sicmutils/complex.cljc, src/sicmutils/env.cljc, src/sicmutils/env/sci.cljc, src/sicmutils/env/sci/macros.cljc, src/sicmutils/numerical/quadrature/adaptive.cljc, src/sicmutils/numerical/quadrature/bulirsch_stoer.cljc, src/sicmutils/polynomial/gcd.cljc, src/sicmutils/polynomial/interpolate.cljc, src/sicmutils/polynomial/richardson.cljc, src/sicmutils/rational_function/interpolate.cljc, src/sicmutils/util/aggregate.cljc, src/sicmutils/util/stream.cljc, test/sicmutils/algebra/fold_test.cljc, test/sicmutils/env/sci_test.cljc, test/sicmutils/polynomial/interpolate_test.cljc, test/sicmutils/rational_function/interpolate_test.cljc, test/sicmutils/util/aggregate_test.cljc, test/sicmutils/util/stream_test.cljc
This PR started as a simple PR to implement kahan-babushka-neumaier summation, described here: https://en.wikipedia.org/wiki/Kahan_summation_algorithm
But of course I had some realizations about how useful folds could be, and went a little bonkers.
- new `sicmutils.algebra.fold` namespace:
- New folds: `kahan-babushka-neumaier` (aliased as `kbn`),
`kahan-babushka-klein` and and `kbk-n` macro for generating higher-order
`kahan-babushka-klein` variants. `generic-sum-fold` folds using
`sicmutils.generic/+`.
- `sicmutils.util.aggregate/kahan-fold` now lives here, named `kahan`.
- `fold->sum-fn` and `fold->scan-fn` generate functions like
`sicmutils.util.aggregate.{sum,scan}` specialized to the supplied fold.
See the docstrings for the multiple arities supported
- fold …
=> New sicmutils.algebra.fold namespace, fold improvements all around

CHANGELOG.md, src/sicmutils/polynomial.cljc, src/sicmutils/rational_function.cljc, src/sicmutils/rational_function/interpolate.cljc, test/sicmutils/polynomial_test.cljc, test/sicmutils/rational_function_test.cljc
- #453:
- Adds `sicmutils.polynomial/from-points` and
`sicmutils.rational-function/from-points` for generating `Polynomial` and
`RationalFunction` instances from sequences of points.
=> Generate polynomial by supplying interpolating points

CHANGELOG.md, src/sicmutils/algebra/fold.cljc, src/sicmutils/util/aggregate.cljc, test/sicmutils/rational_function_test.cljc
Slight performance improvement. Also fixed a test in rational function...
=> call rest before `map present` in scan

CHANGELOG.md, src/sicmutils/abstract/number.cljc, src/sicmutils/polynomial.cljc, src/sicmutils/polynomial/gcd.cljc, src/sicmutils/rational_function.cljc, test/sicmutils/polynomial/gcd_test.cljc, test/sicmutils/polynomial_test.cljc, test/sicmutils/rational_function_test.cljc
- #458:
- Default implementation of `g/negative?` returning `false` for literal
numbers and symbols. This was required to get `g/abs` working for
polynomials and rational functions with symbolic coefficients.
- Polynomials and rational functions now correctly unwrap `Literal`
coefficients in `->expression`. Without this, the resulting expressions
would not correctly respond to `simplify` calls.
- Slight efficiency improvement in
`sicmutils.polynomial.gcd/->content+primitive`.
- `sicmutils.rational-function/from-points` now correctly builds its function.
Before, it was unhygienic; if `'x` appeared in the coefficients the results
would be incorrect.
=> Allow for symbolic rational functions, fix for ->expression

CHANGELOG.md, src/sicmutils/matrix.cljc, test/sicmutils/matrix_test.cljc
- #463 adds a new 1-arity to `sicmutils.matrix/characteristic-polynomial` that
returns an actual polynomial instance. Creating this polynomial once and
calling it many times is much more efficient.
=> Return a polynomial instance from characteristic-polynomial

src/sicmutils/calculus/derivative.cljc, src/sicmutils/series.cljc, src/sicmutils/series/impl.cljc, test/sicmutils/series_test.cljc
After some discussion with GJS I feel good adding back the `x0` argument in `sicmutils.series/function->`, along with clarifying comments.
=> Add x0 argument to function->

CHANGELOG.md, src/sicmutils/polynomial.cljc, src/sicmutils/series.cljc, src/sicmutils/series/impl.cljc, src/sicmutils/special/factorial.cljc, test/sicmutils/polynomial_test.cljc, test/sicmutils/series_test.cljc, test/sicmutils/special/factorial_test.cljc
- #468:
- adds `sicmutils.polynomial/touchard`, implementing a constructor for the
type of polynomial known as a "complete Bell polynomial" or ["Touchard
polynomial"](https://en.wikipedia.org/wiki/Touchard_polynomials).
- adds `sicmutils.special.factorial/bell` for computing the nth [Bell
number](https://en.wikipedia.org/wiki/Bell_number)
- `sicmutils.series/bell-series` returns an infinite sequence of Bell numbers.
=> Add bell numbers, Touchard polynomials

CHANGELOG.md, src/sicmutils/complex.cljc, src/sicmutils/euclid.cljc, src/sicmutils/numbers.cljc, test/sicmutils/complex_test.cljc, test/sicmutils/euclid_test.cljc, test/sicmutils/numbers_test.cljc
- #471:
- installs the complex GCD implementation into the generic system and modifies
it to work with real/complex pairs.
- tweaks the default gcd implementation so that two identical values `x`, even
if they are floating point, will return `x` from `(gcd x x)`. (Really this
should check on their absolute values...)
=> Complex GCD tests, install generic implementation

CHANGELOG.md, src/sicmutils/numbers.cljc, src/sicmutils/polynomial.cljc, test/sicmutils/numbers_test.cljc, test/sicmutils/quaternion_test.cljc
- #474:
- `g/quotient` now supports inexact inputs, as LONG as the inputs are equal up
to sign. So `(g/quotient 1.2 -1.2)` now returns `-1` instead of throwing.
=> Allow quotient between inexact equal floats

CHANGELOG.md, src/sicmutils/numerical/quadrature.cljc, test/sicmutils/mechanics/lagrange_test.cljc
Thanks to @kloimhardt for the repro here: https://github.com/kloimhardt/babashka-snipets
- #480: `sicmutils.numerical.quadrature/definite-integral` now coerces the
result of non-compiled integrands in cljs to double. This prevents the
@kloimhardt bug where certain paths would produce `BigInt` instances and fail
in quadrature calls.
=> Fix CLJS bug with non-compiled definite integrals

CHANGELOG.md, src/sicmutils/polynomial.cljc, test/sicmutils/polynomial_test.cljc
This PR:
- fixes a long-standing (test-only) bug in `sicmutils.polynomial-test` around
palindromic polynomials
- Adds a new `x-degree` argument to `sicmutils.polynomial/univariate->dense`,
for padding the result with zeros in the case that you want to guarantee a
certain dense degree in the result.
=> Fix reciprocal polynomial test bug

CHANGELOG.md, src/sicmutils/numbers.cljc, src/sicmutils/value.cljc, test/sicmutils/numbers_test.cljc
This PR:
- Installs `g/log` and `g/exp` for `js/BigInt` instances, enabling `g/log2` and
`g/log10` in the mix.
- Removes most `js*` calls using `coercive-=` and `js-mod`. This form is
internal and should be avoided.
=> Remove js* forms, enable log, exp for js/BigInt

CHANGELOG.md, src/sicmutils/mechanics/rotation.cljc, src/sicmutils/util/stream.cljc, test/sicmutils/mechanics/rotation_test.cljc
- #491 adds `sicmutils.mechanics.rotation/M->Euler`, for converting from a
rotation matrix to a triple of Euler angles. Now we can successfully round
trip.
=> Add M->Euler to sicmutils.mechanics.rotation

CHANGELOG.md, src/sicmutils/numerical/roots/bisect.cljc, src/sicmutils/util/stream.cljc, test/sicmutils/numerical/roots/bisect_test.cljc
- #490 adds `sicmutils.numerical.roots.bisect` with implementations of bisection
search, secant search and a mixed method found in `scmutils`. These all live
under a `bisect` function.
The data structure returned is similar to the minimization functions in the
`sicmutils.numeric.{unimin, multimin}` namespaces. As more root-finding
methods come online this should all standardize nicely.
=> Add bisect namespace for bisection search

CHANGELOG.md, package.json, src/sicmutils/expression/compile.cljc, test/sicmutils/expression/compile_test.cljc
- #496:
- replaces the function values in `sicmutils.expression.compile` with symbols;
I hadn't realized before that substituting in symbolic `Math/sqrt`, for
example, was possible, vs a `#(Math/sqrt %)` function value. Compiled
functions are now faster!
A simulation run of the double pendulum example in the [clerk-demo
repository](https://github.com/nextjournal/clerk-demo/blob/20a404a271bea29ef98ee4e60a05e54345aa43ba/notebooks/sicmutils.clj)
now runs in 700ms vs the former 2.2 seconds, a major win.
- Function compilation now pre-simplifies numerical forms encountered inside a
function, like `(/ 1 2)`, instead of letting them be evaluated on every fn
call.
- All numerical forms encountered in function compilation are now converted to
either `double` on the JVM or `js/Number` in …
=> Enhance compilation API

CHANGELOG.md, src/sicmutils/expression/compile.cljc, test/sicmutils/expression/compile_test.cljc
- #497:
- `sicmutils.expression.compile/compile-state-fn` and its non-memoized version
can now take an explicit `:mode` argument; this will override the
dynamically bound `*mode*`.
Invalid modes supplied via `:mode` will cause `compile-state-fn` to throw an
exception.
- Fixes a bug where non-numeric operations `up` and `down` were applied at
compile time, throwing an error.
=> Add explicit compilation mode to compile-state-fn

deps.edn, project.clj
This PR bumps clerk to the latest release, which excludes `tools.deps.alpha`.
=> Bump clerk dependency

CHANGELOG.md, src/sicmutils/mechanics/noether.cljc, test/sicmutils/mechanics/noether_test.cljc
This PR adds `sicmutils.mechanics.noether` namespace, with `Noether-integral`.
=> Add noether integral from mechanics package

doc/intro.adoc
Looks like the HTML version moved from https://tgvaughan.github.io to https://tgvaughan.github.io/sicm.
=> Fix link to SICM HTML version
